"""Every number in paper/draft.md, recomputed from the ledger and the traces. Writes paper/numbers.md.

Stdlib only, read-only, no API calls. Nightly episodes only (run_kind), as on the dashboard.
Run it after the data is frozen and paste nothing by hand:

    .venv/bin/python paper/numbers.py
"""
import collections, json, math, random, sqlite3
from pathlib import Path

ROOT = Path(__file__).parent.parent
DB = ROOT / "data" / "ledger.sqlite"
OUT = Path(__file__).parent / "numbers.md"
RUN_GAP_S = 20 * 60           # within a run episodes finish seconds apart; a 20-minute silence is a new run
NIGHTLY = "COALESCE(run_kind, 'nightly') = 'nightly'"
# Wall-clock windows in which the harness was frozen by hand (SIGSTOP). An episode running across one hit its
# 20-minute clock because of the freeze, not the model, so it is excluded. 2026-09-22: paused while offline.
PAUSES = [(1790039238, 1790048675)]   # 2026-09-22T01:07:18Z .. 03:44:35Z
SHORT = {"claude-sonnet-5": "Sonnet 5", "claude-haiku-4-5-20251001": "Haiku 4.5"}


def wilson(k, n, z=1.96):
    if n == 0:
        return (float("nan"),) * 2
    p = k / n; d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d; h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return c - h, c + h


def pct(k, n):
    lo, hi = wilson(k, n)
    return f"{100 * k / n:.1f}% [{100 * lo:.1f}, {100 * hi:.1f}]" if n else "n/a"


def binom_two_sided(k, n):
    """Exact sign test p-value, P(X as or more extreme than k) under Binomial(n, 1/2)."""
    if n == 0:
        return 1.0
    probs = [math.comb(n, i) / 2 ** n for i in range(n + 1)]
    return min(1.0, sum(p for p in probs if p <= probs[k] + 1e-12))


def homogeneity_p(cells, iters=4000, seed=0):
    """Permutation test that one task-model's pass rate is the same in every run. cells: [(passes, n)]."""
    outcomes = [1] * sum(k for k, _ in cells) + [0] * sum(n - k for k, n in cells)
    sizes = [n for _, n in cells]; p = sum(outcomes) / len(outcomes)

    def stat(ks):
        return sum((k - n * p) ** 2 / max(n * p * (1 - p), 1e-9) for k, n in zip(ks, sizes))

    obs = stat([k for k, _ in cells]); rng = random.Random(seed); hits = 0
    for _ in range(iters):
        rng.shuffle(outcomes); i = 0; ks = []
        for n in sizes:
            ks.append(sum(outcomes[i:i + n])); i += n
        hits += stat(ks) >= obs - 1e-9
    return (hits + 1) / (iters + 1)


def table(head, rows):
    return "\n".join(["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
                     + ["| " + " | ".join(str(c) for c in r) + " |" for r in rows])


def main():
    c = sqlite3.connect(DB)
    eps = c.execute(f"SELECT episode_id, ts, family, task_id, model, turns, outcome, label, cost_usd, trace_path "
                    f"FROM episodes WHERE {NIGHTLY} ORDER BY ts").fetchall()
    # Zero-turn and errored episodes are the harness or the network, not agent behaviour (same test as the
    # scheduler's valid-trace count).
    eps = [e for e in eps if (e[5] or 0) > 0 and e[6] in ("pass", "fail", "runaway") and not _straddles(e[9])]
    models = sorted({e[4] for e in eps}, key=lambda m: list(SHORT).index(m) if m in SHORT else 9)
    paired = [m for m in models if m in SHORT]

    # Runs: split the timeline wherever nothing happened for RUN_GAP_S. Time spent paused is not silence:
    # 2026-09-22's first run was frozen for 2.6h and is still one run.
    run_of, run, last = {}, 0, None
    for e in eps:
        paused = sum(max(0, min(b, e[1]) - max(a, last)) for a, b in PAUSES) if last is not None else 0
        if last is not None and e[1] - last - paused > RUN_GAP_S:
            run += 1
        run_of[e[0]] = run; last = e[1]
    # Only episodes from runs where both models were queued count toward paired comparisons.
    runs_models = collections.defaultdict(set)
    for e in eps:
        runs_models[run_of[e[0]]].add(e[4])
    paired_runs = {r for r, ms in runs_models.items() if set(paired) <= ms}
    P = [e for e in eps if run_of[e[0]] in paired_runs]

    out = ["# Numbers for paper/draft.md", "", "Generated by `paper/numbers.py`. Nightly episodes with at least one "
           "turn. 95% Wilson intervals in brackets.", ""]
    out += ["## Corpus", "", table(["", "value"], [
        ["episodes (nightly, turns>0)", len(eps)],
        ["runs", run + 1],
        ["runs with both models (paired)", len(paired_runs)],
        ["episodes in paired runs", len(P)],
        ["distinct tasks in paired runs", len({e[3] for e in P})],
        ["first / last episode (UTC)", f"{_iso(eps[0][1])} / {_iso(eps[-1][1])}"],
        ["agent spend, nightly (USD)", f"{sum(e[8] or 0 for e in eps):.2f}"],
    ]), ""]

    # Headline: pass rate by model and family over the paired runs.
    rows = []
    for m in paired:
        for fam in ("tools", "flakiness"):
            s = [e for e in P if e[4] == m and e[2] == fam]
            k = sum(e[6] == "pass" for e in s)
            spend = sum(e[8] or 0 for e in s)
            rows.append([SHORT[m], fam, len(s), pct(k, len(s)), f"{spend / max(len(s), 1):.4f}",
                         f"{spend / k:.4f}" if k else "n/a"])
    out += ["## Pass rate by model (paired runs)", "",
            table(["model", "family", "n", "pass rate", "USD/episode", "USD/passing episode"], rows), ""]

    # Per task: both models on the same task. Sign test over tasks where the rates differ.
    by = collections.defaultdict(lambda: [0, 0])
    for e in P:
        by[(e[3], e[4])][0] += e[6] == "pass"; by[(e[3], e[4])][1] += 1
    tasks = sorted({e[3] for e in P})
    rows, s_better, h_better = [], 0, 0
    for t in tasks:
        cells = [by.get((t, m), [0, 0]) for m in paired]
        if any(n == 0 for _, n in cells):
            continue
        r = [k / n for k, n in cells]
        s_better += r[0] > r[1]; h_better += r[1] > r[0]
        fam = next(e[2] for e in P if e[3] == t)
        rows.append([t, fam] + [f"{k}/{n}" for k, n in cells] + [f"{100 * (r[0] - r[1]):+.0f}"])
    rows.sort(key=lambda r: float(r[-1]))
    out += ["## Per task, both models", "",
            f"Tasks where Sonnet 5's rate is higher: {s_better}; Haiku 4.5's higher: {h_better}; "
            f"sign test p = {binom_two_sided(min(s_better, h_better), s_better + h_better):.2g}.", "",
            table(["task", "family", "Sonnet 5 pass", "Haiku 4.5 pass", "gap (pts)"], rows), ""]

    # Same prompt, same night, different outcome. Flakiness tasks run several times per run by design.
    cell = collections.defaultdict(lambda: [0, 0])
    for e in P:
        cell[(run_of[e[0]], e[3], e[4])][0] += e[6] == "pass"; cell[(run_of[e[0]], e[3], e[4])][1] += 1
    rows = []
    for m in paired:
        for fam in ("tools", "flakiness"):
            cs = [(k, n) for (r, t, mm), (k, n) in cell.items()
                  if mm == m and n >= 2 and next(e[2] for e in P if e[3] == t) == fam]
            mixed = sum(0 < k < n for k, n in cs)
            rows.append([SHORT[m], fam, len(cs), f"{mixed} ({100 * mixed / max(len(cs), 1):.0f}%)"])
    out += ["## Within-run disagreement", "",
            "A cell is one task, one model, one run, with at least two episodes. Mixed = it both passed and failed.", "",
            table(["model", "family", "cells", "mixed"], rows), ""]

    # Selection control: saturated tasks are retired from the queue, so the active set is by construction
    # the tasks whose pass rates sit away from the extremes -- where repetition produces mixed cells anyway.
    # The retired tasks, run on the same nights by the same harness, are the control for that.
    import yaml
    cfg = yaml.safe_load((ROOT / "config.yaml").read_text())
    retired = set()
    for fam in cfg["families"].values():
        retired |= set(fam.get("retired") or [])
    # Over every nightly run, not just the paired ones: the retired tasks were mostly queued before the
    # second model was added, so a paired-only view contains almost none of them.
    cell_all = collections.defaultdict(lambda: [0, 0])
    for e in eps:
        c2 = cell_all[(run_of[e[0]], e[3], e[4])]
        c2[0] += e[6] == "pass"; c2[1] += 1
    grp_cells = collections.defaultdict(lambda: [0, 0])
    for (r, t, m), (k, n) in cell_all.items():
        if n < 2:
            continue
        g = "retired (saturated)" if t in retired else "active"
        grp_cells[g][0] += 1
        grp_cells[g][1] += 0 < k < n
    out += ["## Selection control: mixed cells, retired vs active tasks", "",
            table(["task group", "cells", "mixed"],
                  [[g, c, f"{mx} ({100 * mx / c:.1f}%)"] for g, (c, mx) in sorted(grp_cells.items())]), ""]

    # Across runs: is a task-model's rate stable from run to run?
    rows, tested = [], 0
    for m in paired:
        for t in tasks:
            cs = [(k, n) for (r, tt, mm), (k, n) in sorted(cell.items()) if mm == m and tt == t and n >= 3]
            if len(cs) < 3:
                continue
            tested += 1
            if len({k / n for k, n in cs}) == 1:
                continue
            p = homogeneity_p(cs)
            if p < 0.05:
                rows.append([SHORT[m], t, " ".join(f"{k}/{n}" for k, n in cs), f"{p:.3f}"])
    out += ["## Across-run instability", "",
            "Task-model pairs seen in 3+ runs with 3+ episodes each whose pass rate differs between runs at "
            f"p < 0.05 (permutation test, uncorrected; read as candidates, not findings). Pairs tested: {tested}; "
            f"expected by chance alone: {0.05 * tested:.1f}.", "",
            table(["model", "task", "passes per run", "p"], rows) if rows else "None.", ""]

    # Failure taxonomy by model.
    labels = collections.Counter((e[4], e[2], e[7] or "not yet labeled") for e in P if e[6] != "pass")
    rows = sorted(([SHORT.get(m, m), f, l, n] for (m, f, l), n in labels.items()), key=lambda r: (r[0], r[1], -r[3]))
    out += ["## Failure labels (paired runs)", "", table(["model", "family", "label", "n"], rows), ""]

    # Serving: which model string the API reported, per requested model.
    served = collections.Counter()
    for e in P:
        try:
            tr = json.loads((ROOT / e[9]).read_text()) if e[9] else None
        except Exception:
            tr = None
        for turn in (tr or {}).get("turns", []):
            served[(e[4], turn.get("served_model") or "not recorded")] += 1
    out += ["## Served model per requested model (turns)", "",
            table(["requested", "served", "turns"], [[m, s, n] for (m, s), n in sorted(served.items())]), ""]

    # Labeler agreement audit. The JSON file holds only the disagreements; the totals are in the run log.
    import re
    try:
        log = (ROOT / "logs" / "label-audit-run-2026-09-14.log").read_text()
        agree, n = map(int, re.search(r"agreement (\d+)/(\d+)", log).groups())
        dis = re.search(r"disagreements: (\{.*\})", log).group(1)
        out += ["## Labeler audit (2026-09-14)", "", f"Haiku 4.5 vs Opus 5 on tool failures both labeled: {agree}/{n} "
                f"agree ({pct(agree, n)}). Disagreements, Haiku -> Opus: {dis}.", ""]
    except Exception:
        pass

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(ROOT)}")


def _straddles(trace_path):
    """True if the episode was running when a pause began."""
    if not trace_path:
        return False
    try:
        t = json.loads((ROOT / trace_path).read_text())
    except Exception:
        return False
    return any(t.get("started", 0) < a < t.get("ended", 0) for a, _ in PAUSES)


def _iso(ts):
    import datetime
    return datetime.datetime.fromtimestamp(ts, datetime.timezone.utc).strftime("%Y-%m-%d %H:%MZ")


if __name__ == "__main__":
    main()
